// <auto-generated />
using Docker.Lecture.Live.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Docker.Lecture.Live.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211110133400_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Docker.Lecture.Live.Data.AppDbContext+Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small Concrete Pants",
                            Year = 2004
                        },
                        new
                        {
                            Id = 2,
                            Name = "Small Steel Bike",
                            Year = 1745
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handmade Steel Keyboard",
                            Year = 1527
                        },
                        new
                        {
                            Id = 4,
                            Name = "Unbranded Metal Table",
                            Year = 1846
                        },
                        new
                        {
                            Id = 5,
                            Name = "Refined Concrete Ball",
                            Year = 1888
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tasty Concrete Hat",
                            Year = 1661
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gorgeous Rubber Table",
                            Year = 1999
                        },
                        new
                        {
                            Id = 8,
                            Name = "Unbranded Rubber Chips",
                            Year = 1575
                        },
                        new
                        {
                            Id = 9,
                            Name = "Handmade Steel Shirt",
                            Year = 1886
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rustic Soft Shoes",
                            Year = 1598
                        },
                        new
                        {
                            Id = 11,
                            Name = "Incredible Granite Chicken",
                            Year = 1710
                        },
                        new
                        {
                            Id = 12,
                            Name = "Awesome Plastic Chicken",
                            Year = 2016
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rustic Rubber Shoes",
                            Year = 1524
                        },
                        new
                        {
                            Id = 14,
                            Name = "Awesome Wooden Fish",
                            Year = 1906
                        },
                        new
                        {
                            Id = 15,
                            Name = "Handcrafted Steel Fish",
                            Year = 1705
                        },
                        new
                        {
                            Id = 16,
                            Name = "Generic Plastic Towels",
                            Year = 1587
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ergonomic Frozen Gloves",
                            Year = 1953
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gorgeous Metal Shoes",
                            Year = 1522
                        },
                        new
                        {
                            Id = 19,
                            Name = "Handmade Wooden Table",
                            Year = 1749
                        },
                        new
                        {
                            Id = 20,
                            Name = "Awesome Wooden Fish",
                            Year = 2001
                        },
                        new
                        {
                            Id = 21,
                            Name = "Tasty Granite Bacon",
                            Year = 1671
                        },
                        new
                        {
                            Id = 22,
                            Name = "Ergonomic Frozen Towels",
                            Year = 1789
                        },
                        new
                        {
                            Id = 23,
                            Name = "Incredible Rubber Car",
                            Year = 1564
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ergonomic Steel Soap",
                            Year = 1510
                        },
                        new
                        {
                            Id = 25,
                            Name = "Unbranded Granite Gloves",
                            Year = 1802
                        },
                        new
                        {
                            Id = 26,
                            Name = "Tasty Soft Fish",
                            Year = 1733
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ergonomic Cotton Gloves",
                            Year = 1747
                        },
                        new
                        {
                            Id = 28,
                            Name = "Handmade Concrete Mouse",
                            Year = 1804
                        },
                        new
                        {
                            Id = 29,
                            Name = "Incredible Soft Table",
                            Year = 1571
                        },
                        new
                        {
                            Id = 30,
                            Name = "Practical Concrete Car",
                            Year = 1588
                        },
                        new
                        {
                            Id = 31,
                            Name = "Practical Soft Towels",
                            Year = 1846
                        },
                        new
                        {
                            Id = 32,
                            Name = "Generic Cotton Chips",
                            Year = 1853
                        },
                        new
                        {
                            Id = 33,
                            Name = "Sleek Cotton Towels",
                            Year = 1524
                        },
                        new
                        {
                            Id = 34,
                            Name = "Licensed Wooden Chair",
                            Year = 1567
                        },
                        new
                        {
                            Id = 35,
                            Name = "Handmade Cotton Bike",
                            Year = 1841
                        },
                        new
                        {
                            Id = 36,
                            Name = "Generic Wooden Bacon",
                            Year = 1530
                        },
                        new
                        {
                            Id = 37,
                            Name = "Fantastic Granite Bacon",
                            Year = 1662
                        },
                        new
                        {
                            Id = 38,
                            Name = "Generic Granite Towels",
                            Year = 1873
                        },
                        new
                        {
                            Id = 39,
                            Name = "Practical Wooden Keyboard",
                            Year = 1588
                        },
                        new
                        {
                            Id = 40,
                            Name = "Gorgeous Steel Bacon",
                            Year = 1885
                        },
                        new
                        {
                            Id = 41,
                            Name = "Sleek Rubber Chips",
                            Year = 1663
                        },
                        new
                        {
                            Id = 42,
                            Name = "Handcrafted Wooden Bacon",
                            Year = 1587
                        },
                        new
                        {
                            Id = 43,
                            Name = "Handmade Plastic Shirt",
                            Year = 1545
                        },
                        new
                        {
                            Id = 44,
                            Name = "Tasty Cotton Towels",
                            Year = 1665
                        },
                        new
                        {
                            Id = 45,
                            Name = "Tasty Granite Ball",
                            Year = 1580
                        },
                        new
                        {
                            Id = 46,
                            Name = "Awesome Metal Car",
                            Year = 1522
                        },
                        new
                        {
                            Id = 47,
                            Name = "Refined Fresh Soap",
                            Year = 1825
                        },
                        new
                        {
                            Id = 48,
                            Name = "Tasty Fresh Pizza",
                            Year = 1852
                        },
                        new
                        {
                            Id = 49,
                            Name = "Awesome Granite Mouse",
                            Year = 2018
                        },
                        new
                        {
                            Id = 50,
                            Name = "Rustic Granite Pants",
                            Year = 1623
                        },
                        new
                        {
                            Id = 51,
                            Name = "Handcrafted Metal Towels",
                            Year = 1658
                        },
                        new
                        {
                            Id = 52,
                            Name = "Small Granite Fish",
                            Year = 1523
                        },
                        new
                        {
                            Id = 53,
                            Name = "Generic Fresh Bike",
                            Year = 1897
                        },
                        new
                        {
                            Id = 54,
                            Name = "Licensed Metal Mouse",
                            Year = 1935
                        },
                        new
                        {
                            Id = 55,
                            Name = "Awesome Frozen Table",
                            Year = 1956
                        },
                        new
                        {
                            Id = 56,
                            Name = "Awesome Concrete Mouse",
                            Year = 1974
                        },
                        new
                        {
                            Id = 57,
                            Name = "Practical Metal Hat",
                            Year = 1765
                        },
                        new
                        {
                            Id = 58,
                            Name = "Gorgeous Rubber Mouse",
                            Year = 1729
                        },
                        new
                        {
                            Id = 59,
                            Name = "Rustic Steel Shoes",
                            Year = 1981
                        },
                        new
                        {
                            Id = 60,
                            Name = "Ergonomic Soft Chips",
                            Year = 1704
                        },
                        new
                        {
                            Id = 61,
                            Name = "Ergonomic Granite Chair",
                            Year = 1578
                        },
                        new
                        {
                            Id = 62,
                            Name = "Generic Wooden Salad",
                            Year = 1966
                        },
                        new
                        {
                            Id = 63,
                            Name = "Incredible Plastic Table",
                            Year = 1603
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ergonomic Granite Tuna",
                            Year = 1752
                        },
                        new
                        {
                            Id = 65,
                            Name = "Practical Metal Pizza",
                            Year = 1671
                        },
                        new
                        {
                            Id = 66,
                            Name = "Tasty Concrete Bacon",
                            Year = 1520
                        },
                        new
                        {
                            Id = 67,
                            Name = "Handcrafted Soft Soap",
                            Year = 1895
                        },
                        new
                        {
                            Id = 68,
                            Name = "Intelligent Concrete Fish",
                            Year = 1924
                        },
                        new
                        {
                            Id = 69,
                            Name = "Tasty Steel Cheese",
                            Year = 1515
                        },
                        new
                        {
                            Id = 70,
                            Name = "Rustic Steel Ball",
                            Year = 1678
                        },
                        new
                        {
                            Id = 71,
                            Name = "Refined Rubber Mouse",
                            Year = 1974
                        },
                        new
                        {
                            Id = 72,
                            Name = "Rustic Frozen Shirt",
                            Year = 1847
                        },
                        new
                        {
                            Id = 73,
                            Name = "Fantastic Steel Shoes",
                            Year = 1732
                        },
                        new
                        {
                            Id = 74,
                            Name = "Unbranded Metal Table",
                            Year = 1968
                        },
                        new
                        {
                            Id = 75,
                            Name = "Handmade Frozen Shoes",
                            Year = 1943
                        },
                        new
                        {
                            Id = 76,
                            Name = "Sleek Wooden Fish",
                            Year = 1526
                        },
                        new
                        {
                            Id = 77,
                            Name = "Generic Rubber Ball",
                            Year = 1500
                        },
                        new
                        {
                            Id = 78,
                            Name = "Handmade Rubber Gloves",
                            Year = 1727
                        },
                        new
                        {
                            Id = 79,
                            Name = "Fantastic Granite Shoes",
                            Year = 1660
                        },
                        new
                        {
                            Id = 80,
                            Name = "Small Fresh Salad",
                            Year = 1847
                        },
                        new
                        {
                            Id = 81,
                            Name = "Fantastic Frozen Shirt",
                            Year = 1590
                        },
                        new
                        {
                            Id = 82,
                            Name = "Licensed Plastic Salad",
                            Year = 1646
                        },
                        new
                        {
                            Id = 83,
                            Name = "Generic Fresh Ball",
                            Year = 1590
                        },
                        new
                        {
                            Id = 84,
                            Name = "Awesome Cotton Pizza",
                            Year = 1871
                        },
                        new
                        {
                            Id = 85,
                            Name = "Unbranded Wooden Gloves",
                            Year = 1769
                        },
                        new
                        {
                            Id = 86,
                            Name = "Handmade Cotton Sausages",
                            Year = 1881
                        },
                        new
                        {
                            Id = 87,
                            Name = "Handcrafted Steel Car",
                            Year = 1702
                        },
                        new
                        {
                            Id = 88,
                            Name = "Rustic Wooden Salad",
                            Year = 1943
                        },
                        new
                        {
                            Id = 89,
                            Name = "Ergonomic Fresh Table",
                            Year = 1781
                        },
                        new
                        {
                            Id = 90,
                            Name = "Handmade Granite Ball",
                            Year = 1656
                        },
                        new
                        {
                            Id = 91,
                            Name = "Handcrafted Frozen Shirt",
                            Year = 1941
                        },
                        new
                        {
                            Id = 92,
                            Name = "Incredible Wooden Salad",
                            Year = 1987
                        },
                        new
                        {
                            Id = 93,
                            Name = "Handcrafted Soft Shirt",
                            Year = 1950
                        },
                        new
                        {
                            Id = 94,
                            Name = "Awesome Cotton Sausages",
                            Year = 1510
                        },
                        new
                        {
                            Id = 95,
                            Name = "Tasty Metal Shoes",
                            Year = 1903
                        },
                        new
                        {
                            Id = 96,
                            Name = "Intelligent Granite Computer",
                            Year = 1743
                        },
                        new
                        {
                            Id = 97,
                            Name = "Tasty Cotton Computer",
                            Year = 1866
                        },
                        new
                        {
                            Id = 98,
                            Name = "Tasty Plastic Chips",
                            Year = 1697
                        },
                        new
                        {
                            Id = 99,
                            Name = "Unbranded Steel Bacon",
                            Year = 1894
                        },
                        new
                        {
                            Id = 100,
                            Name = "Tasty Wooden Shirt",
                            Year = 1777
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
